version: "3.8"

services:
  app:
    image: ghcr.io/aunghein-dev/backend_stocksmanagement:d423ff6dc88369fa0bd2503ee9d4e7cc6c1a168f
    container_name: backend-stock
    restart: unless-stopped
    env_file:
      - /opt/backend-stock/.env
    ports:
      - "127.0.0.1:9999:8080"
    volumes:
      - /data/GeoLite2-City.mmdb:/data/GeoLite2-City.mmdb:ro
