version: "3.8"
services:
  app:
    image: ghcr.io/aunghein-dev/backend_stocksmanagement:b0a0254c1b4b7734761650714bfca9484c3a6f91
    container_name: backend-stock
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: 
      SPRING_DATASOURCE_USERNAME: 
      SPRING_DATASOURCE_PASSWORD: 
      JWT_SECRET: 
      MEDIA_CLEANUP_SECRET: 
      SUPABASE_URL: 
      SUPABASE_API_KEY: 
      SUPABASE_BUCKET: 
      APP_GEOIP_DATABASE_PATH: /data/GeoLite2-City.mmdb
      JAVA_OPTS: >
        -Xms128m -Xmx256m
        -XX:+UseSerialGC
        -XX:MaxMetaspaceSize=128m
        -XX:MaxDirectMemorySize=64m
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - "127.0.0.1:9999:8080"
    volumes:
      - /data/GeoLite2-City.mmdb:/data/GeoLite2-City.mmdb:ro
