version: "3.8"
services:
  app:
    build:
      context: .
    container_name: backend-stock
    ports:
      - "127.0.0.1:9999:8080"
    restart: unless-stopped
    environment:
      - APP_GEOIP_DATABASE_PATH=/data/GeoLite2-City.mmdb
    volumes:
      - /data/GeoLite2-City.mmdb:/data/GeoLite2-City.mmdb:ro
